"""your message

Revision ID: a1b99c6127a9
Revises: 6e20bf280b83
Create Date: 2025-07-22 00:23:09.412771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b99c6127a9'
down_revision: Union[str, Sequence[str], None] = '6e20bf280b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diplomas', sa.Column('hot_reload_test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diplomas', 'hot_reload_test')
    # ### end Alembic commands ###
