"""generalized the document model

Revision ID: a4034945471e
Revises: 354127ae5e43
Create Date: 2025-07-31 03:03:28.772062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4034945471e'
down_revision: Union[str, Sequence[str], None] = '354127ae5e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diploma_files_id'), table_name='diploma_files')
    op.drop_table('diploma_files')
    op.add_column('diplomas', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diplomas', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diplomas', type_='foreignkey')
    op.drop_column('diplomas', 'document_id')
    op.create_table('diploma_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('diploma_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['diploma_id'], ['diplomas.id'], name=op.f('diploma_files_diploma_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('diploma_files_uploaded_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('diploma_files_pkey'))
    )
    op.create_index(op.f('ix_diploma_files_id'), 'diploma_files', ['id'], unique=False)
    # ### end Alembic commands ###
