"""changed statustype enum to accomodate needs

Revision ID: b18e84fa38c7
Revises: d0109b9dac81
Create Date: 2025-08-06 13:33:09.144093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18e84fa38c7'
down_revision: Union[str, Sequence[str], None] = 'd0109b9dac81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
