"""changed document_type to type on documents table as the prefix is unnecessary 

Revision ID: b35e908d5a38
Revises: 5987c5efc987
Create Date: 2025-08-08 10:36:18.590351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b35e908d5a38'
down_revision: Union[str, Sequence[str], None] = '5987c5efc987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. add new column nullable with a temporary server default (DDL level)
    op.add_column(
        'documents',
        sa.Column(
            'type',
            sa.Enum('id_card', 'previous_diploma', 'new_diploma', 'transcript', 'other', name='documenttypeenum'),
            nullable=True,
            server_default='new_diploma'
        )
    )
    # 2. back-fill from old column
    op.execute("UPDATE documents SET type = document_type")
    # 3. enforce NOT NULL
    op.alter_column('documents', 'type', nullable=False)
    # 4. drop the temporary default (optional)
    op.alter_column('documents', 'type', server_default=None)
    # 5. drop old column
    op.drop_column('documents', 'document_type')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_type', postgresql.ENUM('id_card', 'previous_diploma', 'new_diploma', 'transcript', 'other', name='documenttypeenum'), autoincrement=False, nullable=False))
    op.drop_column('documents', 'type')
    # ### end Alembic commands ###
