"""changed diploma status model

Revision ID: d0109b9dac81
Revises: eebde5e9d4f0
Create Date: 2025-08-06 12:41:57.001751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0109b9dac81'
down_revision: Union[str, Sequence[str], None] = 'eebde5e9d4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diploma_statuses', 'previous_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diploma_statuses', sa.Column('previous_status', postgresql.ENUM('PENDING', 'IN_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED', 'SUSPENDED', name='statustype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
