"""added cascade delete to the diploma stasuses to attempt fixing the fk issue on delete

Revision ID: e0d68a729e6c
Revises: 2a70af5fbfa0
Create Date: 2025-09-08 14:47:35.250790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d68a729e6c'
down_revision: Union[str, Sequence[str], None] = '2a70af5fbfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
