"""changed document and diploma tables to have an fk on document only

Revision ID: eebde5e9d4f0
Revises: 3513e7bd9f1d
Create Date: 2025-08-06 09:46:11.297883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebde5e9d4f0'
down_revision: Union[str, Sequence[str], None] = '3513e7bd9f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('diplomas_document_id_fkey'), 'diplomas', type_='foreignkey')
    op.drop_column('diplomas', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diplomas', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('diplomas_document_id_fkey'), 'diplomas', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
